git clone git@github.com:gsej/code-samples.git ../repos/code-samples
git clone git@github.com:gsej/coding-exercise.git ../repos/code-exercises
git clone git@github.com:gsej/concatenate-code.git ../repos/concatenate-code
git clone git@github.com:gsej/dotfiles.git ../repos/dotfiles
git clone git@github.com:gsej/gsej.github.io.git ../repos/gsej.github.io	
git clone git@github.com:gsej/internet-monitor.git ../repos/internet-monitor
git clone git@github.com:gsej/notes.git ../repos/notes
git clone git@github.com:gsej/osinstall.git ../repos/osinstall
git clone git@github.com:gsej/play.git ../repos/play
git clone git@github.com:gsej/polytunnel-monitor.git ../repos/polytunnel-monitor	
git clone git@github.com:gsej/PSDevTools.git ../repos/PSDevTools
git clone git@github.com:gsej/share-prices.git ../repos/share-prices
git clone git@github.com:gsej/youinvest.git ../repos/youinvest
git clone git@github.com:gsej/youinvest-csv-files.git ../repos/youinvest-csv-files