[ ! -d ../repos/code-samples ] && git clone git@github.com:gsej/code-samples.git ../repos/code-samples
[ ! -d ../repos/code-exercises ] && git clone git@github.com:gsej/coding-exercise.git ../repos/code-exercises
[ ! -d ../repos/concatenate-code ] && git clone git@github.com:gsej/concatenate-code.git ../repos/concatenate-code
[ ! -d ../repos/gsej.github.io ] && git clone git@github.com:gsej/gsej.github.io.git ../repos/gsej.github.io	
[ ! -d ../repos/internet-monitor ] && git clone git@github.com:gsej/internet-monitor.git ../repos/internet-monitor
[ ! -d ../repos/notes ] && git clone git@github.com:gsej/notes.git ../repos/notes
[ ! -d ../repos/play ] && git clone git@github.com:gsej/play.git ../repos/play
[ ! -d ../repos/polytunnel-monitor ] && git clone git@github.com:gsej/polytunnel-monitor.git ../repos/polytunnel-monitor	
[ ! -d ../repos/PSDevTools ] && git clone git@github.com:gsej/PSDevTools.git ../repos/PSDevTools
[ ! -d ../repos/share-prices ] && git clone git@github.com:gsej/share-prices.git ../repos/share-prices
[ ! -d ../repos/youinvest ] && git clone git@github.com:gsej/youinvest.git ../repos/youinvest
[ ! -d ../repos/youinvest-csv-files ] && git clone git@github.com:gsej/youinvest-csv-files.git ../repos/youinvest-csv-files
[ ! -d ../repos/backup ] && git clone git@github.com:gsej/backup.git ../repos/backup
[ ! -d dailycodingproblems ] && git clone git@github.com:gsej/dailycodingproblems.git ../repos/dailycodingproblems
